# Generated by Django 2.2.4 on 2021-10-23 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('road_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('longitude', models.DecimalField(decimal_places=12, max_digits=15)),
                ('latitude', models.DecimalField(decimal_places=12, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='RoadType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
        migrations.AddField(
            model_name='road',
            name='road_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='road_app.RoadType'),
        ),
    ]
